Repository rapidsai/deployment, pull requests merged in 2023-01, with the labels that each got.

#111 Add related examples
  extensions/rapids_related_examples.py
  source/cloud/aws/sagemaker.md
  source/conf.py
  source/examples/rapids-sagemaker-higgs/notebook.ipynb
  source/examples/rapids-sagemaker-higgs/rapids-higgs.py
Labels: sphinx

#114 DOC: Add dask cloud provider example with Azure MNMG
  source/cloud/azure/azure-vm-multi.md
Labels: doc, cloud/azure

#118 Add notebook gallery with tag filter
  extensions/rapids_related_examples.py
  source/_includes/menus/aws.md
  source/_includes/menus/azure.md
  source/_includes/menus/gcp.md
  source/_includes/menus/ibm.md
  source/_static/css/custom.css
  source/_static/js/notebook-gallery.js
  source/_templates/notebooks-tag-filter.html
  source/conf.py
  source/examples/index.md
  source/examples/rapids-sagemaker-higgs/notebook.ipynb
  source/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.ipynb
  source/guides/index.md
  source/index.md
  source/platforms/index.md
Labels: sphinx

#119 Add related examples to all pages
  extensions/rapids_related_examples.py
  source/cloud/aws/ec2.md
  source/cloud/aws/ecs.md
  source/cloud/aws/eks.md
  source/cloud/azure/aks.md
  source/cloud/azure/azure-vm-multi.md
  source/cloud/azure/azure-vm.md
  source/cloud/azure/azureml.md
  source/cloud/gcp/compute-engine.md
  source/cloud/gcp/dataproc.md
  source/cloud/gcp/gke.md
  source/cloud/gcp/vertex-ai.md
  source/cloud/ibm/virtual-server.md
  source/guides/azure/infiniband.md
  source/guides/mig.md
  source/platforms/coiled.md
  source/platforms/kubeflow.md
  source/platforms/kubernetes.md
  source/tools/kubernetes/dask-helm-chart.md
  source/tools/kubernetes/dask-kubernetes.md
  source/tools/kubernetes/dask-operator.md
  source/tools/rapids-docker.md
Labels: sphinx

#121 Add notebook tag sidebar
  extensions/rapids_related_examples.py
  source/_static/css/custom.css
  source/_static/js/notebook-gallery.js
  source/_templates/notebooks-tags.html
  source/conf.py
Labels: sphinx

#122 Fix duplicated entries in examples sidebar section nav
  extensions/rapids_related_examples.py
Labels: sphinx

#123 Add Grid Toctree custom directive
  extensions/rapids_grid_toctree.py
  source/conf.py
  source/guides/index.md
  source/index.md
  source/platforms/index.md
  source/tools/index.md
Labels: sphinx

#124 Add docs for notebook extension
  .gitignore
  README.md
  source/images/theme-notebook-tags.png
  source/images/theme-tag-style.png
Labels: doc, sphinx
