Repository rapidsai/deployment, pull requests merged in 2024-10, with the labels that each got.

#435 switch to miniforge in build-and-deploy job
  .github/workflows/build-and-deploy.yml
Labels: improvement, non-breaking

#436 simplify markdownlint configuration
  .markdownlintignore
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#440 update EC2 instructions (button text changed)
  source/cloud/aws/ec2.md
Labels: improvement, non-breaking

#438 remove commented-out 'autogluon' installs
  source/cloud/aws/sagemaker.md
  source/cloud/azure/azureml.md
Labels: improvement, non-breaking

#450 fix version in dask-cuda link
  source/tools/dask-cuda.md
Labels: bug, non-breaking

#451 Google Colab: clarify language, remove outdated links
  source/platforms/colab.md
Labels: improvement, non-breaking, cloud/gcp

#446 SageMaker example: make downloads conditional
  pyproject.toml
  source/examples/rapids-sagemaker-higgs/notebook.ipynb
Labels: improvement, non-breaking

#456 Fix code typo for Coiled
  source/platforms/coiled.md
Labels: platform/coiled

#458 Fix EKS instructions for 24.10 testing
  source/cloud/aws/eks.md
Labels: cloud/aws

#472 fix image rendering in rapid-sagemaker-hpo notebook
  source/examples/rapids-sagemaker-hpo/notebook.ipynb
Labels: cloud/aws
