Repository rapidsai/deployment, pull requests merged in 2024-08, with the labels that each got.

#404 simplify and fix optuna-hpo notebook
  .gitignore
  source/examples/rapids-optuna-hpo/notebook.ipynb
Labels: example

#405 gitignore common extensions with sensitive data, update pre-commit hooks
  .gitignore
  .pre-commit-config.yaml
Labels: non-breaking, hygiene

#408 simplify SageMaker docs
  source/cloud/aws/sagemaker.md
  source/examples/rapids-sagemaker-higgs/notebook.ipynb
  source/images/sagemaker-containerize-and-publish.png
Labels: improvement, non-breaking, cloud/aws

#414 update CODEOWNERS
  .github/CODEOWNERS
Labels: non-breaking, hygiene

#413 remove cufile.log in xgboost-randomforest-gpu-hpo-dask example
  source/examples/xgboost-randomforest-gpu-hpo-dask/cufile.log
Labels: non-breaking, hygiene

#415 remove unused images
  source/_static/images/examples/rapids-autoscaling-multi-tenant-kubernetes/jupyter-lab-dashboard.png
  source/_static/images/examples/rapids-sagemaker-hpo/airline_dataset.png
  source/_static/images/examples/rapids-sagemaker-hpo/header.png
  source/_static/images/examples/rapids-sagemaker-hpo/sagemaker_notebook_instance.png
  source/_static/images/examples/rapids-sagemaker-hpo/v2_overview.png
Labels: non-breaking, hygiene

#416 Add unused images pre-commit check
  .pre-commit-config.yaml
  scripts/unused_images.sh
  source/images/kubeflow-rapids-install.png
Labels: build/test, hygiene

#412 use CUDA 12.5 and Python 3.11 in most examples
  source/conf.py
Labels: improvement

#403 point to new dask-cuda docs, ensure nightly deployment docs point to nightly RAPIDS API docs
  README.md
  extensions/rapids_version_templating.py
  source/conf.py
  source/examples/rapids-sagemaker-higgs/notebook.ipynb
  source/examples/rapids-sagemaker-hpo/notebook.ipynb
  source/examples/xgboost-azure-mnmg-daskcloudprovider/notebook.ipynb
  source/examples/xgboost-dask-databricks/notebook.ipynb
  source/examples/xgboost-randomforest-gpu-hpo-dask/notebook.ipynb
  source/guides/scheduler-gpu-requirements.md
  source/hpc.md
  source/platforms/databricks.md
  source/platforms/kubeflow.md
  source/tools/dask-cuda.md
  source/tools/kubernetes/dask-helm-chart.md
Labels: doc
